### ISSUE TITLE
Fix publicPath in 03 demo and other suggestions

### ISSUE THREAD

**Issue by erdoll** [jods4/aurelia-webpack-build#17]
Joel,

Thank you very much for putting this documentation and demonstrations together.

I have been waiting for this release of aurelia webpack 2.0 before starting a conversion of my projects from systemjs to webpack.

I am going through your demonstrations.  They all work fine using your npm run web script.  However, when I run webpack from command line, then run a web server (I am using http-server), the 03-Code_splits do not run properly in the browser.

With 03-Code_splits, a request is being made for disthello.js with the default route and about (with no .js) when I try to go to the about route directly in the URL. from the server with a 404 response.

Change publicPath to "/dist/" to get this working properly. 

It would be nice if you added a <require> for a css file in one of your views to demonstrate that.

Also, a short explanation in your document about the optional second parameter in PLATFORM.moduleName would be a good addition.  You use the 2nd parameter in app.ts for route moduleId.

I found when starting to integrate your demo code into my code base that 
  import { PLATFORM } from 'aurelia-framework';
needed to be changed to 
  import { PLATFORM } from "aurelia-pal"; 
to make either Visual Studio or Resharper happy to stop squiggly line warnings. The aurelia-framework.d.ts imports PLATFORM, but does not re-export it.

Again, thanks for all this helpful guidance.

**Comment by jods4** [comment]
Thanks for your suggestions.

I will change all `publicPath` to `/dist/`, this indeed makes a difference in some use-cases. I already changed it in the ASPNET demo to enable HMR.

The second parameter to `moduleName` is introduced here: 
https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies#code-splitting

Maybe you don't have the latest `aurelia-framework` release (1.1.0) because everything from `aurelia-pal` is re-exported by `aurelia-framework`.
This happens here in the code:
https://github.com/aurelia/framework/blob/master/dist/es2015/aurelia-framework.js#L415
And is reflected in the typescript definition:
https://github.com/aurelia/framework/blob/master/dist/aurelia-framework.d.ts#L238

**Comment by erdoll** [comment]
Missed that section on the 2nd parameter to moduleName.

Delete of node_modules and fresh npm install cleared up the intellisense problem. npm must have been playing tricks on me.

**Comment by jods4** [comment]
I have updated all demos to use `publicPath: '/dist/'` instead of just `dist`.
