### ISSUE TITLE
Support chunking

### ISSUE THREAD

**Issue by jods4** [jods4/aurelia-webpack-build#2]
From @niieani
> the two problems you mentioned as "not worked out yet", I have already thought about extensively. The reason I introduced PLATFORM.moduleName(name, { configuration }) is so that we can configure dynamic dependencies, including split-points and lazy-loaded ones. aurelia-loader-webpack handles those cases natively (i.e. detects bundle-loader uses, as long as they're named accordingly by the module renamer)

**Comment by jods4** [comment]
I now have an example with 2 different pages that are (with their dependencies) split into one chunk each, which is loaded on demand.

All it takes is passing a chunk name: `PLATFORM.moduleName('my-page', 'chunk-name')`.

**Comment by niieani** [comment]
Would you consider supporting a configurable object instead of a string passed in the second parameter? This would allow for potential extensions of the `moduleName` API in the future.

**Comment by jods4** [comment]
I am trying to make this as simple as possible for the common case.
But the string could be a shortcut and we could accept an object if we wanted to add extra options.
Maybe `moduleName(string, string | { chunk: string, ... })`.
Do you have any option in mind? I can't think of anything...

**Comment by niieani** [comment]
Yes, I do. I don't think it's a good idea to make the second parameter a "chunk-name string OR object", because the chunk name might not be present in other build systems (it might be a webpack-only concept), while other options might be more universal. Here's the interface I have defined so far: https://github.com/aurelia/pal/blob/master/src/index.js#L157-L170

**Comment by jods4** [comment]
We don't need to name that string `chunk`, but if you do code splitting (the concept), which is no doubt the most useful option, you need a way to group what goes together and what is separated. An arbitrary key string is probably the most natural way to do that?
What I mean is that this string can map to `chunk` in webpack and to something else in other packaging systems (e.g. be a new entry point in requirejs).

Looking at the options you have over there: 
- `chunk`, NC ;)
- `lazy`, what's this exactly? The webpack lazy concept doesn't apply here, is this something else?
- `moduleRegex`, can you tell me more about that?

**Comment by niieani** [comment]
The idea of `lazy` is to apply the bundle-loader with the `lazy=true` query option to the given module (e.g. equivalent of `require.include('bundle-loader?lazy&chunk=someChunk!./some-module')`) -- at least in Webpack. It would have to work differently in RJS or other loaders, but its definitely implementable outside of Webpack.

`moduleRegex` would be used to override the set of included files based on the provided regex, instead of the moduleName (first parameter). This makes sense when the moduleName is completely dynamic, or when we wish to limit the inferred regex to a specific set of files, e.g. when we call:

```js
PLATFORM.moduleName('./submodule/' + someVar, {
  moduleRegex: /^submodule\/sub-\w+\.js$/
})
```

The above example might be a bit contrived, but I hope that gives you the idea of what's it for.

**Comment by jods4** [comment]
The bundle-loader `lazy` context makes no sense here. It is meant to be used at the loading site but `PLATFORM.moduleName()` is not the loading site. It is just a static declaration of a dynamic dependency that might be requested by `aurelia-loader`. The loading site _is_ `aurelia-loader-webpack` but it always operate the same and does not expose a `lazy` option.

Let me explain that better. In my Aurelia build, you get a proxy module `async!x` that exports a function `r(cb)`, which will load the other chunk if needed and pass the actual module `x` to the callback `cb` when loaded.
If the bundle is lazy, everything happens when calling `r()`: load the file, return `x`.
If the bundle is eager, requesting `async!x` will immediately load the file from the network. `x` will still be executed and returned when calling `r()` but its chunk might have already been loaded at that point.

The goal of this API is to let the user request `async!x` in advance, for example so that it can parallelize other module loads. And _later_ use all those modules. For example:
```ts
// Everything is eager
let rx = request('async!x');  // file loads
let ry = request('async!y');  // file loads in parallel
let x = await x(); // should be a callback not await but you get the idea
let y = await y();

// Everything is lazy
let rx = request('async!x');  // nothing happens yet
let ry = request('async!y');  // nothing happens yet
let x = await x(); // file loads (wait)
let y = await y(); // file loads (sequentially)
```

But inside `aurelia-loader-webpack`, the two calls immediately follow one another:
```ts
// Hardcoded sequence inside aurelia-loader-webpack
let proxy = request('async!x');
return proxy();
```
Using eager loading here makes no visible difference but the module code is larger and it allocates one extra array.
That's why the dependencies for Aurelia are always lazy in my plugin.

**Comment by jods4** [comment]
A few comments about `moduleRegex`. 
OK, this is the globbing part which I haven't talked yet.

1. Do we need an additional regex? Webpack itself parses expressions like your `'./submodule/' + someVar` (I currently don't) but I don't think there is additional support to limit what is actually matched by that, is it?
So if webpack gets away with just that, do we need to add extra complexity?

2. I'm trying to think of the actual use cases here. The only one that I could come up with is dynamic expressions in `<list repeat.for='item of cart'><compose view.bind='item.view'></list>`. 
But I'm really not sure we need globbing to cover this case. We could add the dependency to the item type, for example:
```ts
class RedItem {
  get view() { return PLATFORM.moduleName('red-view'); }
}
```
or we could list the supported item types as dependencies of the list view model:
```ts
// These are possible view dependencies, 
// It will turn out as dead code that gets removed by uglify and co.
PLATFORM.moduleName('red-view');
PLATFORM.moduleName('blue-view');
PLATFORM.moduleName('green-view');

class ListViewModel { }
```

What do you think?
Do you have another use case that would warrant usage of a pattern in `moduleName()`?

**Comment by niieani** [comment]
I believe we're still talking about two different things.

Obviously, every call to load a module will be asynchronous, unless the module is cached. That's the design of the aurelia-loader. The `lazy: true` is solving an entirely different problem. It's like an annotation that tells the bundler: 

"Hey Bundler, I don't want this module to be added to this bundle! Instead, make a new bundle and put the module and its dependencies into that new bundle, then give me a `callback()` that will fetch the bundle and return the module, once I call that callback."

`aurelia-loader-webpack` handles this case, because when it cannot find the module synchronously, from the module cache, it will search for `async!module-name` ---> this is our callback, [which is then executed](https://github.com/aurelia/loader-webpack/blob/master/src/aurelia-loader-webpack.ts#L126) and finally the module is returned in the `Promise`.

The underlying module is loaded into the caches (both the Webpack cache and the aurelia-loader cache), so this will never happen more than once.

**Comment by jods4** [comment]
> Hey Bundler, I don't want this module to be added to this bundle

Read my examples and explanations again. This is not what `lazy` means. `bundle!` always create another chunk. What `lazy` changes is at which moment exactly that chunk is fetched on the network.

**Comment by niieani** [comment]
> Do you have another use case that would warrant usage of a pattern in `moduleName()`?

In the last year people have developed so many edge-cases, that warrant such an addition. Webpack does indeed get away with `'string' + var` combos, but it does allow you to define whether it should add subdirectories or not. Since we need to create a regex from the `'string' + var` combo, we might as well support overwriting for more granular control.

As for dead code from `PLATFORM.moduleName('red-view');`, I think it would be better to make another pattern for simply including modules, without turning them into strings. Perhaps `PLATFORM.moduleInclude(/regexOrStringOrArrayOfEither/)`.

> `bundle!` always create another chunk. 

As far as I understand, `bundle-loader` does not always create another chunk. If you specify a chunk-name of a pre-existent chunk, it will merge the module to that chunk, not create a new one. But this is beside the point. The `lazy: true` is a shortcut for `bundle-loader?lazy`, not just to add the `bundle-loader` without query parameters.

**Comment by jods4** [comment]
RE: patterns, I agree with the flexibility of a regex or a glob but I would like to see some of those edge-cases to know what we're designing for. I don't like adding concepts without an application.
Note that strings have another advantage: webpack will complain if you made a typo, so in my first example (inside the item itself) it would be a good static check. A regex has no compile-time validation.

> If you specify a chunk-name of a pre-existent chunk, it will merge the module to that chunk, not create a new one.

That is of course correct but unrelated to `lazy`.

What lazy changes is this:
```js
// lazy bundle!abc 
module.exports = function(cb) {
  require.ensure([], function(require) {
    cb(require("abc"));
  }, "chunkname");

// eager bundle!abc
var cbs = [], data;
module.exports = function(cb) {
  if(cbs) cbs.push(cb);
  else cb(data);
};
require.ensure([], function(require) {
  data = require("abc");
  var callbacks = cbs;
  cbs = null;
  for(var i = 0, l = callbacks.length; i < l; i++) {
    callbacks[i](data);
  }
}, "chunkname");

```

**Comment by niieani** [comment]
> That is of course correct but unrelated to `lazy`.

Actually it is related, because of how `require.ensure` behaves. If I remember correctly, if you make multiple `require.ensure`s with the same `chunkname` (3rd parameter), it'll still reuse the same, provided chunk (and add to it), not create a new one.

**Comment by jods4** [comment]
> If I remember correctly, if you make multiple require.ensures with the same chunkname (3rd parameter), it'll still reuse the same, provided chunk (and add to it), not create a new one.

Yes, that is again correct but still unrelated to `lazy`. 
Notice how in the codegen above, whether lazy or not, the same `require.ensure([], function, "chunkname")` call is emitted.

**Comment by niieani** [comment]
Of course I also agree that regex is less debuggable. Perhaps an option like `recursive: boolean` to indicate whether we want to dig into the `variable+'string'` path recursively might be a good medium ground. 

I don't have good examples at hand, because I didn't ever have such needs, however we've had users who had those patterns of dynamically loading (I know cause I've debugged them), so they will happen for sure.

> the same `require.ensure([], function, "chunkname")` call is emitted.

The key is that the same `require.ensure` isn't executed in the `lazy` case, unless the `callback()` is explicitly called. Eager executes regardless of the callback, as soon as the module is loaded.
