### ISSUE TITLE
Pug templating

### ISSUE THREAD

**Issue by gbouteiller** [jods4/aurelia-webpack-build#22]
Hello,
I'm trying to use the webpack plugin with pug templating.
So I've configured webpack :
```js
module: {
    rules: [
      { test: /\.ts$/i, loader: 'awesome-typescript-loader', options: { configFileName: 'tsconfig.webpack.json' } },
      { test: /\.pug$/i, loaders: [ 'html-loader', 'pug-html-loader' ] },
    ]
  },  

  plugins: [
    new AureliaPlugin( { viewsExtensions: '.pug' } ),
  ],
```
`app.pug` is correctly added to my bundle but it seems that the bundle is looking for `app.html` moduleID. In the documentation, there is a `html-resources-loader` that is mentioned but I don't know where it is and if it is something I have to configure.
Thank you for your help and great work by the way!

**Comment by jods4** [comment]
In your build, you'll want to add `aurelia-webpack-plugin/html-requires-loader` between `html-loader` and `pug-html-loader`.

This loader parses your HTML and looks for `<require>`, `<compose view="" viewModel="">` to ensure their dependencies are included.

I don't think this is your problem, though.
More likely, you have not reconfigured the Aurelia _runtime_ to look for `.pug` instead of `.html` when loading views by convention.
This is done by `ViewLocator.prototype.convertOriginToViewUrl`, see [this comment](https://github.com/aurelia/skeleton-navigation/issues/396#issuecomment-207823852) for an example that uses Jade templates.

**Comment by gbouteiller** [comment]
Thank you very much, it works! I didn't know about `ViewLocator.prototype.converOriginToViewUrl`.
