### ISSUE TITLE
How to use PLATFORM.moduleName with dynamic <compose>?

### ISSUE THREAD

**Issue by nashwaan** [jods4/aurelia-webpack-build#28]
Lets say a user can change the widgetName during application run from `calendar` to `meeting`.
If we do this, the browser gives this error `Error: Unable to find module with ID: meeting`

From my understanding, the following line will not tell webpack which module id to load as value of `widgetName` is not known during webpack compile time.
```html
<compose view-model.bind="widgetName"></compose>
```

So, should I use `PLATFORM.moduleName()` with `compose` elements and how?

**Comment by jods4** [comment]
The strings `calendar` and `meeting` have to exist somewhere in your code. That's where you should wrap them with `moduleName`.
Bonus: by doing so you also get compile-time validation that your module names actually exist.

**Comment by nashwaan** [comment]
> The strings `calendar` and `meeting` have to exist somewhere in your code. That's where you should wrap them with `moduleName`.

Any example on how to do this, please? (Note the module could be a pair of .js/.html, .js only or .html only)

**Comment by nashwaan** [comment]
Initially, I thought I have to follow the [wiki](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies):

> Here are a few common Aurelia APIs that take module names:
> 
> Routes { moduleId: "xxx" }
> .plugin("xxx")
> .feature("xxx") But see below!
> .globalResources("xxx")
> @useView("xxx")
> .setRoot("xxx")
> All of those must be wrapped inside PLATFORM.moduleName("xxx").

But, this is what I did and it works:

```js
import {PLATFORM, bindable} from 'aurelia-framework';
PLATFORM.moduleName('./calendar');
PLATFORM.moduleName('./meeting');
```

Thanks alot @jods4 .

**Comment by nashwaan** [comment]
I think adding explicit documentation about how to use `PLATFORM.moduleName()` for `<compose>` in the wiki will be helpful for other developers.

**Comment by jods4** [comment]
You should not use them randomly like that, but where they naturally happen.

You need to have somewhere in your code something similar to this:
```ts
class ViewModel {
 widgetName: PLATFORM.moduleName('calendar');

  changeWidget() {
    this.widgetName = PLATFORM.moduleName('meeting');
  }
}
```

I strongly advise you to use absolute names.

**Comment by erdoll** [comment]
I am facing the same issue as @nashwaan.

I am databinding to a view name that is not a literal string like 'calender', but a string retrieved from a web service at runtime.  

Your example, of having the 

     PLATFORM.moduleName('./meeting'); 

used somewhere in the code is not valid, as the I never have the module designated by a string anywhere in my code.

I used the workaround of @nashwaan above by putting code like

     PLATFORM.moduleName('./meeting');

in my app.js.  

That does work for data-driven <compose> view-model.bind(ing).  

Since I have about two dozen of these data selected modules, I will likely move all of these statements into a resource to be included at the main.js file.

Is there a more webpacky way to force webpack to include modules not explicitly found by the plugin?

Again - thanks so much for putting this wiki and demos together.

**Comment by jods4** [comment]
@erdoll In that case, rather than littering your code with strings that don't exist I would rather use `ModuleDependenciesPlugin` (for a handful) or `GlobDependenciesPlugin` (for batches) in your webpack config to handle the 100% dynamic case at runtime.

Choose a module where it makes sense to attach the dependencies (probably where the server call happens), and if for example you have all the dynamic views used at runtime in a specific folder you can do:
```js
new GlobDependenciesPlugin({ "requesting-module": "products/dynamic-views/*.ts" })
```
See also: https://github.com/jods4/aurelia-webpack-build/wiki/Secondary-plugins#globdependenciesplugin

**Comment by erdoll** [comment]
GlobDependenciesPlugin was just what I needed.
