### ISSUE TITLE
What about multi Aurelia apps under /src or a nested app e.g. /src/nested

### ISSUE THREAD

**Issue by jack4it** [jods4/aurelia-webpack-build#35]
Hey, I'm seeing a scenario that one could have a nested Aurelia app for example **/src/nested/main.js** along the main app **/src/main.js**. Regarding the webpack config, how would the **entry** config look like? So far, the most popular way of specifying an entry is simply like `entry: { main: "aurelia-bootstrapper" }`. In this nested app case, how would we define the entry for it? How we can instruct the plugin to use for example **/src/nested/main** as the app entry point?

**Comment by jods4** [comment]
The simplest solution is to use 2 separate webpack.config / compilations.

If you don't want to do that, there's some specific configuration steps you have to take,
I haven't tried myself but the following should work:

1. Make your entry points based on this model:
```js
// main1.js
import "aurelia-polyfills"; // unless you don't need them
import "aurelia-loader-webpack";
import "aurelia-bootstrapper";

export function configure(aurelia) {...};
```

2. Avoid doing more than that in this file because manipulating Aurelia before it's initialized leads to problems.
Of course `aurelia-app` in your html starting points must be set accordingly.

3. Pass `noWebpackLoader: true` option to `AureliaPlugin`

4. Set `aureliaApp: undefined`. This property is meant to make Webpack aware of the first module id that Aurelia will load at startup, as defined by `aurelia-app` in your html. Because you build for multiple entry points, you can't use a single default value of `main` anymore.

   a. _Either_ replace `aureliaApp` by an additional `moduleName` call with your `aurelia-app` value inside your entry point, like so:
   ```js
   // main1.js
   /* imports as above... */
   import { PLATFORM } from "aurelia-pal";
   
   PLATFORM.moduleName("main");  // Put the `aurelia-app` from this entry point html
   export function configure(aurelia) {...};
   ```

   b. _Or_ Don't use `aurelia-app` attribute at all and pass the module you want to load to `setRoot` during bootstrap, properly wrapped in `moduleName`.
   ```js
   // main1.js
   // ...
   export function configure(aurelia) {
      // ...
      aurelia.start().then(_ => aurelia.setRoot(PLATFORM.moduleName("main"));
   };
   ```

// 5. This setup does not support Webpack DLL
**EDIT:** it should, just not in the DLL-producing config.

6. If you use `CommonsChunkPlugin` to move shared code (like libs) in their own chunk, **do not move `aurelia-loader-webpack`** out of the entry chunks.  This one is special and it _has to be_ in the Webpack entry chunk(s).

**Comment by jack4it** [comment]
Thanks for the FLASH response, @jods4 rocks!
I tried and chose the two compilations approach. I kept the entry point for the nested app simply as: nested: "aurelia-bootstrapper", in the AureliaPlugin options, i give it an app name like nested/main, also in the app.html. The last trick seems to be that in the nested main.js, the setRoot call has to use the same nested/app as well.
Hope this helps for someone else with a similar use case.

**Comment by jods4** [comment]
Shall we close this issue then?

**Comment by netrounds-joakim** [comment]
@jods4  Hmm so if I simply create 2 compilations in this case, there's no way to share common code between the those right? No way to use `CommonsChunksPlugin` and such things?

Because I think I will go with the 2 compilations solution for now, until I understand these things better.

Also are there any plans to add multiple entry points support like this to work with the plugin? As I understand it now, the plugin is designed for the use case where Aurelia is a "one page app", right?

I'm all new to webpack, aurelia and most of this so sorry if I'm asking obvious questions. Thank you

**Comment by jods4** [comment]
@netrounds-joakim You are correct, the plugin API is designed for single entry point (SPA) first.
With steps from that other comment, I see no reason why multiple entry points would not work, but it's hard to figure that out on your own without a deep understanding of how Aurelia+Webpack+the plugin work together.
If this is common enough, maybe I should think about adding simpler support for multiple entry points. (There's no plan right now, but why not?)

Using 2 compilations will be simpler at the moment, for sure. Because a Webpack config is just javascript you can easily extract the common part, then just change the entry point in each. That's really easy stuff with no code duplication.

Sharing common code is slightly harder. Using a webpack DLL can achieve that. You'll have 3 compilations then: the shared part (DLL) + each entry point.

The Webpack DLL plugin is something that Aurelia plugin does support, more info:
https://github.com/jods4/aurelia-webpack-build/wiki/Using-Webpack-DLL

**Comment by netrounds-joakim** [comment]
@jods4 thank you for the quick reply :)

> If this is common enough, maybe I should think about adding simpler support for multiple entry points. (There's no plan right now, but why not?)

You have on vote from me at least! And maybe @jack4it ?

> Using 2 compilations will be simpler at the moment, for sure. Because a Webpack config is just javascript you can easily extract the common part, then just change the entry point in each. That's really easy stuff with no code duplication.

Ok yea I assumed something like that would be possible so then I know that plan of mine will work.

> Sharing common code is slightly harder. Using a webpack DLL can achieve that. You'll have 3 compilations then: the shared part (DLL) + each entry point.

Ok thank you for that pointer. I had seen mentions of DLL but did not fully understand what they were for, but that makes sense.

Thanks!

**Comment by jods4** [comment]
Shortly, a Webpack "DLL" is a separate Webpack compilation unit that produces a re-usable bundle that other Webpack compilations can reference.

Without this, each Webpack compilation is totally autonomous and distinct.

**Comment by netrounds-joakim** [comment]
Ok thanks for the clarification :)

**Comment by alexdresko** [comment]
@jods4 I would super love to be able to support multiple Aurelia apps from a single webpack config. I've spent probably more than a dozen hours trying to make it work (with the DLL plugin, of course), and can't seem to get anywhere. 

I can't be the only person who needs multiple Aurelia apps in the same application. `dotnet new Aurelia` is a fantastic starting point, but it seems like developers who are coming from a more traditional ASP.NET development experience are going to be more comfortable having Aurelia within individual pages, at least in the beginning. For example, a customer area might be entirely different from an admin area. 

That's one thing that makes Vue so enticing -- You include a reference to Vue.js in a page, and you're practically up and running.

Is there not some way of including multple AureliaPlugins and using various combinations of aureliaapp and entry? Or is it always going to add everything to the first aurelia-bootstrapper chunk? 

You don't have to give a long winded reply... I've just spent a lot of time on this and I'd love to know that I'm not crazy.

**Comment by jods4** [comment]
@alexdresko Have your tried the steps in my first answer?

If you follow them you should be able to create a single webpack config with multiple entry points (one for each of your page).

**Comment by alexdresko** [comment]
@jods4 Well, no, because you said "This setup does not support Webpack DLL" and I've already got that in place and working great. If you think it'll work with DLL, I'll give it a try. 

Thanks for replying. I don't feel alone in this anymore. :)

**Comment by jods4** [comment]
So you want multiple DLL compilations + multiple entry points in your main config?
Out of curiosity, what's your motivation for that setup?

Currently the code in `AureliaPlugin` would not support multiple entry points with DLLs.
Note that `AureliaPlugin` itself is only a (large) collage + configuration of many other smaller dedicated plugins. If you're hardcore you could redo that collage yourself with an appropriate configuration for multiple DLLs... I'm not advising you to, it's hard. 😅

**Comment by jods4** [comment]
@alexdresko I've reviewed the RC3 config and I believe it now could work with DLL (not in the DLL producing config of course but a multi-entry point Aurelia config should also work when consuming DLLs, provided you configure everything properly).

I have updated my answer above with some corrections if you want to try.

**Comment by alexdresko** [comment]
I have a DLL for Aurelia and a DLL for Bootstrap et al. That seems to work well with a single Aurelia entry point. It also works well for standard Razor pages that just need the latter DLL and their page-specific script. 

Where I'm stuck is creating a second Aurelia entry point. I don't know enough about the plugin, but I'm fairly confident that the current version of the plugin is the source of my problems. I probably _could_ reverse engineer the plugin, but then I might be missing out on future enhancements/fixes. 

Also, I'm surprised I made it this far. I feel I'm living inside a very fragile house here.

**Comment by alexdresko** [comment]
Awesome! I'll give it a go in the next day or two! Is worth a try if you have at least some suspicion that it might work.

**Comment by jods4** [comment]
Let me know how it goes.

**Comment by danielmeza** [comment]
Hi @jods4  I folow your steps to cofigure two app with a single config file but it dosn´t work. When I set the noWebpackLoader: true I get this error `No PLATFORM.Loader is defined and there is neither a System API (ES6) or a Require API (AMD) globally available to load your app.`  throw by aurelia-bootstrapper.
In my entry file I set the imports but it cand not configure the Loader propertly because the loader must be configured before to load the entry point.

**Comment by alexdresko** [comment]
I experienced the same problem a few weeks ago when I tried the instructions but didn't say anything because I figured I was just following the instructions correctly. Thanks for validating my attempt. Was going to try again, but procrastination wins this round!

**Comment by jods4** [comment]
To be sure: did you use the prolog above in each of your entry point modules? 
They should include `import "aurelia-loader-webpack"`, see above.

Let me know if that helps or not.

**Comment by alexdresko** [comment]
@jods4 Tried again tonight. You can see my full attempt, including the steps I ran through here: https://github.com/alexdresko/multiautest

Everything was working fine until I attempted to follow the instructions (https://github.com/alexdresko/multiautest/commit/2de492b819a7ca62435f6e262f71efdc4acae537)

At the end of the steps I detailed, you can see the error message I'm getting. Not sure if that's because of how I configured the entry point in `webpack.config.js`.

  

> Error: Unable to find module with ID: bootFirst
>       at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:187)
>       at step (aurelia-loader-webpack.js:36)
>       at Object.next (aurelia-loader-webpack.js:17)
>       at aurelia-loader-webpack.js:11
>       at new Promise (<anonymous>)
>       at 55.__awaiter (aurelia-loader-webpack.js:7)
>       at WebpackLoader.55.WebpackLoader._import (aurelia-loader-webpack.js:152)
>       at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:252)
>       at step (aurelia-loader-webpack.js:36)
>       at Object.next (aurelia-loader-webpack.js:17)

I tried to be as thorough as possible with my repro. 

Note that the repro _should_ be running against the latest version of everything. 

@danielmeza Given @jods4 is a busy man, it might be helpful if you could take a look and see where I went wrong.

**Comment by jods4** [comment]
@alexdresko I believe Aurelia tries to load `bootFirst` when starting up because it's in the `aurelia-app` attribute here:
https://github.com/alexdresko/multiautest/blob/master/Views/Home/Index.cshtml#L5

And that's exactly what `aureliaApp` option in the Webpack plugin takes care of.

I have edited my checklist above to indicate how to adjust for that in a multi entrypoint situation. See points 4a or 4b.

**Comment by alexdresko** [comment]
@jods4 I've run out of time to work on this during my lunch break, but I did have some great success!  4a worked great. I updated the repo if anyone wants to see what I did, though I wouldn't exactly recommend it as a "best practices" example. Anyone who is truly curious what steps need to be taken should review the commit log, as I tried to use that as a way to document the process. 

I'm even using the common chunks plugin in the example. 

I do want to go back and do some analysis on the webpack output, though. It seems like the common.js is too big... it's practically as big as the vendor.js, which doesn't seem right. 

4b didn't work for me.  I assume this is what you meant by the instructions 

![image](https://user-images.githubusercontent.com/333022/32119133-4649a126-bb22-11e7-86f7-0a4aba2ea664.png)

I presume that was the only change I needed to make since I was already calling `setRoot`... unless you wanted me to use a different module in set root? 

With that change, I would always get this error:

![image](https://user-images.githubusercontent.com/333022/32119148-52de472a-bb22-11e7-927d-d9d7126a66d8.png)

And if I totally removed the aurelia-app attribtue from the html, the page would just sit at "loading..."

**Comment by jods4** [comment]
I really meant remove it completely. You can pass the DOM element into which Aurelia should inject to app to `setRoot` instead.

**Comment by danielmeza** [comment]
@jack4it @alexdresko  Hi guis, sorry for my delay, I'm to busy to. I will send my feedback this weekend, cause I  tried many configurations.

**Comment by domenkogler** [comment]
I am posting a [working example](https://github.com/domenkogler/skeleton-navigation/tree/master/multiple-entries) of multiple entry points with webpack 4. 
Warning: Custom changes are needed to html-webpack-plugin, as is in [this PR](https://github.com/jantimon/html-webpack-plugin/pull/944).
