### ISSUE TITLE
Dynamic <compose> tutorial?

### ISSUE THREAD

**Issue by m0ngr31** [jods4/aurelia-webpack-build#36]
This is similar to #28, but mine looks similar to this: `<compose view="../patterns/${patterns}.html"></compose>`. How do I do PLATFORM.moduleName on a dynamic HTML file that has no ViewModel to go with it?

I tried using various version of this: `new GlobDependenciesPlugin({'pattern-index': './src/apps/pattern-library/patterns/**/*.html'}),`, but I can't get it working yet. What am I doing wrong?

**Comment by jods4** [comment]
The fact that it's `.html` or `.js` doesn't change anything as far as the build is concerned. The module just has to be referenced somehow.

As in previous answers I would like to first suggest binding to the full module name if that's reasonable. That means the module name actually appears somewhere in your code and you can wrap that with `moduleName`.

With rare exceptions, I also recommend using absolute module names rather than relative when using Webpack (the `../patterns` part).

When it comes to `GlobDependenciesPlugin`:
- note that the path starts in your `webpack.config.js` folder.
- a glob should _not_ start with `.`. Try `src/apps/pattern-library/patterns/**/*.html`.

**Comment by m0ngr31** [comment]
> As in previous answers I would like to first suggest binding to the full module name if that's reasonable. That means the module name actually appears somewhere in your code and you can wrap that with moduleName.

Unfortunately, that isn't something viable otherwise I'd do that.

> With rare exceptions, I also recommend using absolute module names rather than relative when using Webpack (the ../patterns part).

It seems to get the right path: `Unhandled rejection Error: Unable to find module with ID: apps/pattern-library/patterns/intro/patterns.html` I just need to get it as a module somehow.

I did try without the `.`, but the same result. I'm assuming it's something else stupid I'm doing.

**Comment by jods4** [comment]
Arf I know why.
`pattern-index` is supposed to be the module id that depends on those globs.
Clearly that's not correct.

Probably more like `apps/pattern-library/patterns/pattern-index` or something similar.

**Comment by m0ngr31** [comment]
Sorry, I'm pretty new to webpack, so I'm kind of dense.
Same error as before, but just with a different name:

```
ERROR in ./src/apps/pattern-library/app.js
Module not found: Error: Can't resolve 'apps/pattern-library/patterns/pattern-index'
```

**Comment by jods4** [comment]
Since I'm not seeing your config, code structure and file names you need to adjust the names when I guess wrong.

`GlobDependenciesPlugin` adds extra dependencies to the graph that Webpack builds to pack your app.

Specifically, its parameter is an object whose:
- keys are modules that must have additional dependencies, e.g. can be the view with `<compose>`;
- values are glob patterns to find the extra dependencies.

If you need more help please provide more info, such as the organization of your code.

**Comment by m0ngr31** [comment]
Hopefully this can help you get a better idea:
![image](https://user-images.githubusercontent.com/1045977/28533075-1052bcba-7059-11e7-87ec-37ef7f41eb13.png)

So it looks like this:
-src
--apps
---pattern-library
---(other-folders)
-webpack.config.js

**Comment by jods4** [comment]
Not completely but I will give it a try anyway:
` { "apps/pattern-library/app.html": "src/apps/pattern-library/patterns/**/*.html" }`

**Comment by m0ngr31** [comment]
So if I manually do this: `new GlobDependenciesPlugin({'apps/pattern-library/patterns/intro/patterns.html': 'src/apps/pattern-library/patterns/intro/patterns.html'}),` it works fine, but as soon as I try to do the wildcard HTML it causes issues. If there a different/better way to accomplish that?

**Comment by m0ngr31** [comment]
Scratch everything I said earlier, this was the trick: `new GlobDependenciesPlugin({'apps/pattern-library/app.html': 'src/apps/pattern-library/patterns/**/*.html'}),` just as you said it would be (I was trying to be too specific with module naming)

**Comment by eric-914** [comment]
I'm adding my 2¢ for troubleshooting tips:  I found that `GlobDependenciesPlugin` doesn't work if the components are in the same folder as the module referencing them.  Once I moved the components into a subfolder, and updated `GlobDependenciesPlugin` it finally started adding them to the bundle.

**Comment by EMooreMAC** [comment]
I've been banging my head trying to get this to work, and can't figure out the paths. Given the example above, can someone explain why the path to the _dependent_ module is relative to the 'src' folder, and the path to the dependencies is relative to the root? Given that the webpack.config.js is in the root, I would expect that the path to the dependent module would be relative to the root, and the path to the dependencies is relative to either the root, or to the dependent module, but neither seems to be the case.

**Comment by jods4** [comment]
@EMooreMAC 
The dependent module is resolved according to your webpack configuration, as any other module reference would be. Assuming you have in your webpack config `resolve.modules = ["node_modules", "src"]`, this explains why it appears to be relative to `src`. 
In reality it is not "relative to src" and you can refer to a 3rd party module `aurelia-dialog`, use aliases, etc.

The dependencies are glob. They are not directly modules and can't easily be resolved according to your config. To start with, when you have more than one folder in `resolve.modules` it would be unclear in which one to look, or ambiguous if several matched.
So they are glob evaluated as paths on the file system, from your root folder.

Hope this clarifies things up a little bit.
