### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stoffeastrom** [jods4/aurelia-webpack-build#7]
I wanted to try this but I must have missed something. After clone I go into the `Webpack` folder and run `npm i`. Then I go into for example `demos/03-Code_splits` and run `npm i ../Webpack` and then `npm i` and then `npm run web`. When I goto `localhost:8080` I get the following error

```javascript
Uncaught (in promise) Error: Unable to find module with ID: aurelia-framework
    at WebpackLoader.<anonymous> (main.js:16513)
    at step (main.js:16351)
    at Object.next (main.js:16332)
    at main.js:16326
    at 54.__awaiter (main.js:16322)
    at WebpackLoader.54.WebpackLoader._import (main.js:16469)
    at WebpackLoader.<anonymous> (main.js:16578)
    at step (main.js:16351)
    at Object.next (main.js:16332)
    at main.js:16326
(anonymous) @ main.js:16513
step @ main.js:16351
(anonymous) @ main.js:16332
(anonymous) @ main.js:16326
54.__awaiter @ main.js:16322
54.WebpackLoader._import @ main.js:16469
(anonymous) @ main.js:16578
step @ main.js:16351
(anonymous) @ main.js:16332
(anonymous) @ main.js:16326
54.__awaiter @ main.js:16322
54.WebpackLoader.loadModule @ main.js:16565
(anonymous) @ main.js:9934
Promise.reject (async)
rejected @ main.js:16324
Promise.reject (async)
step @ main.js:16325
(anonymous) @ main.js:16326
54.__awaiter @ main.js:16322
54.WebpackLoader.loadModule @ main.js:16565
(anonymous) @ main.js:9934
Promise.resolve (async)
(anonymous) @ main.js:9931
Promise.resolve (async)
(anonymous) @ main.js:9924
```
I obviously missed something but what :)?

**Comment by jods4** [comment]
It really depends which version you've cloned ;)
Note that the last version committed here needs some `npm link` hackery to work from your disk (but it's the most stable/simple/complete).

Given your description I think you have an older release and managed to get it running.
The problem is some missing dependencies in Aurelia libs currently available on NPM.
In the meantime, you can import `ModuleDependenciesPlugin` from the webpack folder and add this gist to your plugins:
https://gist.github.com/jods4/600ded3c31b48c4d1a9e03855d54e1e2

That should help.

**Comment by stoffeastrom** [comment]
The clone includes the latest typescript conversion.. I will fiddle around.. hopefully this will get in soon enough :). Thanks for your reply. Regarding the missing npm I noticed that the other day since I wanted to use the `aurelia-bootstrapper@^2.0.0` and the `aurelia-loader-nodejs` has a recent name fix that isn't released. It's quite nice to run `aurelia-testing` with `nodejs` directly in vs code with `ctrl + alt + t` :)

**Comment by jods4** [comment]
ok, here's a few hints to get you started with the latest commit then.

The `Webpack` folder contains a built `aurelia-webpack-plugin@2.0.0-rc` version. No need to npm install. Now the problem for you is that you can't just `aurelia-webpack-plugin: "^2.0.0"` in your `package.json` because it's not published on NPM yet. For now you must `npm link` it.

Here's how:
- Make sure you have the `aurelia-webpack-plugin` dev dependency in your `project.json`, no matter what version. This is ok in the demos.
- First run `npm link` in the `Webpack` folder. This will tell npm that you might want to use this local package.
- At the root of your project (e.g. `demos/02-Traced_deps`) run `npm link aurelia-webpack-plugin`. This will tell npm to use the local version defined before instead of the online one.
- Now you can `npm install`. If you look inside the `node_modules` you will see a symbolic link to the local folder for `aurelia-webpack-plugin`.

The second tricky thing is that the demos work on new, unpublished aurelia libraries that document their dynamic dependencies. In the meantime, you can use the plugin mentionned above and the dependencies from the gist instead.

You may have similar problems with 3rd-party libs, as no lib has proper dependency documentation for the new plugins at the moment.

Before publishing this, we want to do some real-world tests, so feel free to ping me in gitter if you need help getting this to work. 

Anyway, please let me know how it goes!

**Comment by stoffeastrom** [comment]
The first part I'm already familiar with (npm link) but it was the second part with the gist above that fixed it💥 . I'm converting a plugin of mine to typescript and already had a "old" demo setup with webpack but I wanted to slim it down! I will play around with this... 👍
