### ISSUE TITLE
Use of aurelia-pal differ between wiki and demo

### ISSUE THREAD

**Issue by krokofant** [jods4/aurelia-webpack-build#8]
In the wiki it's stated that `aurelia-pal@1.2.0` is a prerequisite and the following example is given for it's use:
```
import { PLATFORM } from "aurelia-pal";

aurelia.use.plugin(PLATFORM.moduleName("aurelia-validation"));
```

Yet, in the demo `aurelia-pal` isn't in the deps and the uses of it seems global. I'm sure this will be more clear when it's fully released but could you clarify why there is this difference?

Thanks for your work!

**Comment by jods4** [comment]
Indeed I should probably change my demos...

What happens is that in a webpack build with the new `AureliaPlugin`, it does not actually matter where `PLATFORM.moduleName` comes from. It is completely erased during build.

In principle, you should import it from `aurelia-pal` and this is especially true if you distribute a library. `aurelia-pal` provides a default implementation that just returns its first parameter. This is important if your code is consumed by a build system other than webpack and the call is not removed from the code.

My demos cheat somehow and I should update them to reflect the best practice. Because it will be removed from the code at build time, I use non-existent global objects. To make Typescript happy, I declare this fake global inside `PLATFORM.d.ts`.

Let me know if this new plugin works for you!

**Comment by krokofant** [comment]
Works amazingly! I didn't even know webpack 2 was released so this was a great intro 🌈
